In [1]:
round(3.45,1)

3.5

In [2]:
from decimal import Decimal 
a = Decimal(1.5)
b = Decimal(1.5)
a + b

Decimal('3.0')

In [3]:
x = 2.456788999
format(x, '0.3f')
format(x, '^10.1f')

'   2.5    '

In [4]:
x = 232
hex(x)

'0xe8'

In [5]:
bin(x)

'0b11101000'

In [6]:
oct(x)

'0o350'

In [11]:
data = '\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)

In [13]:
x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

In [14]:
z = complex(2,4)
z

(2+4j)

In [20]:
import math
p = float('inf')
math.isinf(p)

True

In [16]:
s = float('-inf')

In [21]:
import math
r = float('nan')
math.isnan(r)

True

In [22]:
from fractions import Fraction
a = Fraction(1,2)
b = Fraction(1,2)
print(a+b)

1


In [23]:
a.numerator

1

In [24]:
a.denominator

2

In [25]:
float(a)

0.5

In [29]:
import numpy as np
x = np.array([2,4,6,8])
y = np.array([5,10,15,20])

x*2

array([ 7, 14, 21, 28])

In [30]:
x+y

array([ 7, 14, 21, 28])

In [31]:
x*y

array([ 10,  40,  90, 160])

In [32]:
 grid = np.zeros(shape=(10000,10000), dtype=float)
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [33]:
b = np.array([[2,4,6,8], [5,10,15,20]])
b

array([[ 2,  4,  6,  8],
       [ 5, 10, 15, 20]])

In [37]:
b[0]

array([2, 4, 6, 8])

In [36]:
b[:0]

array([], shape=(0, 4), dtype=int64)

In [38]:
u = np.matrix([[4,-2,6],[1,7,0],[2,6,-4]])
u

matrix([[ 4, -2,  6],
        [ 1,  7,  0],
        [ 2,  6, -4]])

In [39]:
u.T

matrix([[ 4,  1,  2],
        [-2,  7,  6],
        [ 6,  0, -4]])

In [41]:
u.I

matrix([[ 0.16666667, -0.16666667,  0.25      ],
        [-0.02380952,  0.16666667, -0.03571429],
        [ 0.04761905,  0.16666667, -0.17857143]])

In [42]:
import random 
x = [2,4,6,8,10]
random.choice(x)

4

In [43]:
random.choice(x)

6

In [44]:
random.choice(x)

4

In [45]:
random.choice(x)

4

In [46]:
random.shuffle(x)
x

[10, 2, 4, 6, 8]

In [47]:
x

[10, 2, 4, 6, 8]

In [48]:
random.randint(0,100)

19

In [49]:
random.randint(0,100)

41

In [50]:
random.randint(0,100)

15

In [51]:
random.random()


0.0321484109756871

In [52]:
random.random()

0.7775657488489366

In [53]:
random.uniform(1.2, 10.75)

8.448789119887971

In [54]:
random.uniform(1.2, 10.75)

4.222870443565255

In [55]:
#I learned a lot from this lab today. First off I learned the function to 
#round numerical values and a format function to make float values look different 
#depending on what syntax you use. I also learned about about the many different libraries 
#like Numpy and math that make it much easier deal with numeric lists and values. But my favorite 
#thing I probably learned today was that I could create a list with more than one row. Overrall, I would so 
#Python is a pleasent language to work with so far. 